const dummyProduct = {
  availableForSale: true,
  collections: {
    edges: [
      {
        node: {
          id: "1",
          title: "A",
        },
      },
      {
        node: {
          id: "3",
          title: "Rhude",
        },
      },
      {
        node: {
          id: "5",
          title: "Hello Kitty",
        },
      },
    ],
  },
  createdAt: "2020-08-19T09:23:10Z",
  description: "Another great product for testing one two three",
  descriptionHtml:
    "<p>Another great product for testing</p>\n<ol>\n<li>one </li>\n<li>two</li>\n<li>three</li>\n</ol>",
  handle: "variation-product",
  id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzU1NDMxNjU1NTg5NDM=",
  images: {
    edges: [
      {
        node: {
          id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMTg1MTU4NzQ0NDc1MTk=",
          altText: null,
          originalSrc:
            "https://cdn.shopify.com/s/files/1/0460/0014/4543/products/shells.jpg?v=1597828993",
        },
      },
      {
        node: {
          id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMTg1MTU4NzQ0ODAyODc=",
          altText: null,
          originalSrc:
            "https://cdn.shopify.com/s/files/1/0460/0014/4543/products/konstantinata.jpg?v=1597828994",
        },
      },
      ,
    ],
  },
  metafields: { edges: [] },
  onlineStoreUrl: "https://stoffbua.myshopify.com/products/variation-product",
  options: [
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0T3B0aW9uLzcwOTU3OTk2NzcwODc=",
      name: "Size",
      values: ["big", "medium", "small"],
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0T3B0aW9uLzcwOTU3OTk3MDk4NTU=",
      name: "Color",
      values: ["blue", "white", "gray"],
    },
    ,
  ],
  priceRange: {
    minVariantPrice: { amount: "75.0", currencyCode: "NOK" },
    maxVariantPrice: { amount: "75.0", currencyCode: "NOK" },
  },
  productType: "Jewellery",
  publishedAt: "2020-08-19T14:43:24Z",
  tags: [],
  title: "variation product",
  updatedAt: "2020-08-21T07:50:51Z",
  variants: {
    edges: [
      {
        node: {
          availableForSale: true,
          compareAtPrice: "100.00",
          compareAtPriceV2: [Object],
          id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zNTc0MDI5MTY5NDc1MQ==",
          image: [Object],
          metafields: [Object],
          price: "75.00",
          priceV2: [Object],
          requiresShipping: true,
          selectedOptions: [
            { name: "Size", value: "big" },
            { name: "Color", value: "blue" },
          ],
          sku: "var-prod-200",
          title: "big / blue",
          weight: 1,
          weightUnit: "KILOGRAMS",
          presentmentPrices: [Object],
        },
      },
      {
        node: {
          availableForSale: true,
          compareAtPrice: "100.00",
          compareAtPriceV2: [Object],
          id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zNTc0MDI5MTcyNzUxOQ==",
          image: [Object],
          metafields: [Object],
          price: "75.00",
          priceV2: [Object],
          requiresShipping: true,
          selectedOptions: [Array],
          sku: "var-prod-201",
          title: "big / white",
          weight: 1,
          weightUnit: "KILOGRAMS",
          presentmentPrices: [Object],
        },
      },
      {
        node: {
          availableForSale: true,
          compareAtPrice: "100.00",
          compareAtPriceV2: [Object],
          id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zNTc0MDI5MTc2MDI4Nw==",
          image: [Object],
          metafields: [Object],
          price: "75.00",
          priceV2: [Object],
          requiresShipping: true,
          selectedOptions: [Array],
          sku: "var-prod-202",
          title: "big / gray",
          weight: 1,
          weightUnit: "KILOGRAMS",
          presentmentPrices: [Object],
        },
      },
      {
        node: {
          availableForSale: true,
          compareAtPrice: "100.00",
          compareAtPriceV2: [Object],
          id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zNTc0MDI5MTc5MzA1NQ==",
          image: [Object],
          metafields: [Object],
          price: "75.00",
          priceV2: [Object],
          requiresShipping: true,
          selectedOptions: [Array],
          sku: "var-prod-203",
          title: "medium / blue",
          weight: 1,
          weightUnit: "KILOGRAMS",
          presentmentPrices: [Object],
        },
      },
      {
        node: {
          availableForSale: true,
          compareAtPrice: "100.00",
          compareAtPriceV2: [Object],
          id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zNTc0MDI5MTgyNTgyMw==",
          image: [Object],
          metafields: [Object],
          price: "75.00",
          priceV2: [Object],
          requiresShipping: true,
          selectedOptions: [Array],
          sku: "var-prod-204",
          title: "medium / white",
          weight: 1,
          weightUnit: "KILOGRAMS",
          presentmentPrices: [Object],
        },
      },
      {
        node: {
          availableForSale: true,
          compareAtPrice: "100.00",
          compareAtPriceV2: [Object],
          id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zNTc0MDI5MTg5MTM1OQ==",
          image: [Object],
          metafields: [Object],
          price: "75.00",
          priceV2: [Object],
          requiresShipping: true,
          selectedOptions: [Array],
          sku: "var-prod-205",
          title: "medium / gray",
          weight: 1,
          weightUnit: "KILOGRAMS",
          presentmentPrices: [Object],
        },
      },
      {
        node: {
          availableForSale: true,
          compareAtPrice: "100.00",
          compareAtPriceV2: [Object],
          id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zNTc0MDI5MTk1Njg5NQ==",
          image: [Object],
          metafields: [Object],
          price: "75.00",
          priceV2: [Object],
          requiresShipping: true,
          selectedOptions: [Array],
          sku: "var-prod-206",
          title: "small / blue",
          weight: 1,
          weightUnit: "KILOGRAMS",
          presentmentPrices: [Object],
        },
      },
      {
        node: {
          availableForSale: true,
          compareAtPrice: "100.00",
          compareAtPriceV2: [Object],
          id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zNTc0MDI5MjAyMjQzMQ==",
          image: [Object],
          metafields: [Object],
          price: "75.00",
          priceV2: [Object],
          requiresShipping: true,
          selectedOptions: [Array],
          sku: "var-prod-207",
          title: "small / white",
          weight: 1,
          weightUnit: "KILOGRAMS",
          presentmentPrices: [Object],
        },
      },
      {
        node: {
          availableForSale: true,
          compareAtPrice: "100.00",
          compareAtPriceV2: [Object],
          id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zNTc0MDI5MjEyMDczNQ==",
          image: [Object],
          metafields: [Object],
          price: "75.00",
          priceV2: [Object],
          requiresShipping: true,
          selectedOptions: [],
          sku: "var-prod-208",
          title: "small / gray",
          weight: 1,
          weightUnit: "KILOGRAMS",
          presentmentPrices: [Object],
        },
      },
    ],
  },
  vendor: "Stoffbua",
};

const dummyTopics = [
  {
    title: "first",
  },
  {
    title: "second",
  },
  {
    title: "third",
  },
];

const dummyProducts = [
  { sku: "DUMMY-01", price: 2 },
  { sku: "DUMMY" },
  { sku: "DUMMY-02", price: 3 },
  { sku: "DUMMY-03", price: 4 },
  { sku: "NEW-03", price: 4 },
  { sku: "NEW" },
];
const dummyShopifyCategories = [
  { id: 402, name: "Hello Kitty" },
  { id: 403, name: "Karl Lagerfeld " },
  { id: 404, name: "Maybelline" },
  { id: 405, name: "Rhude" },
  { id: 406, name: "Rubiks" },
  { id: 407, name: "Sue Tsai" },
  { id: 504, name: "Sonic" },
  { id: 408, name: "Tetris" },
];
const dummyCrystallizeTopics = [
  { id: "5e6f7612e749b9001cee6568", name: "Hello Kitty" },
  { id: "5e6f7612e749b9001cee6569", name: "Karl Lagerfeld " },
  { id: "5e6f7612e749b9001cee656a", name: "Maybelline" },
  { id: "5e6f7612e749b9001cee656b", name: "Rhude" },
  { id: "5e6f7612e749b9001cee6567", name: "Select" },
  { id: "5e6f7613e749b9001cee6572", name: "Palmeiras" },
  { id: "5e6f7612e749b9001cee6570", name: "Sonic" },
  { id: "5e6f7613e749b9001cee657e", name: "Basquete" },
];

const dummyShoppifyOrder = {
  Name: "#11111",
  Email: "testUser@gmail.com",
  "Financial Status": "paid",
  "Paid at": "",
  "Fulfillment Status": "fulfilled",
  "Fulfilled at": "2020-09-15 14:01:03 +0200",
  "Accepts Marketing": "no",
  Currency: "EUR",
  Subtotal: "2.95",
  Shipping: "0.00",
  Taxes: "0.00",
  Total: "2.95",
  "Discount Code": "",
  "Discount Amount": "0.00",
  "Shipping Method": "",
  "Created at": "2020-09-08 07:42:58 +0200",
  "Lineitem quantity": "1",
  "Lineitem name": "Nina",
  "Lineitem price": "2.95",
  "Lineitem compare at price": "",
  "Lineitem sku": "",
  "Lineitem requires shipping": "true",
  "Lineitem taxable": "true",
  "Lineitem fulfillment status": "fulfilled",
  "Billing Name": "Bill Testson",
  "Billing Street": "Billingstr 123",
  "Billing Address1": "Billingstr 123",
  "Billing Address2": "Billingstr 123",
  "Billing Company": "compbil",
  "Billing City": "bilcity",
  "Billing Zip": "123456",
  "Billing Province": "",
  "Billing Country": "PL",
  "Billing Phone": "123456",
  "Shipping Name": "Bill Testson",
  "Shipping Street": "Billingstr",
  "Shipping Address1": "Billingstr",
  "Shipping Address2": "",
  "Shipping Company": "",
  "Shipping City": "ShipCity",
  "Shipping Zip": "2222",
  "Shipping Province": "",
  "Shipping Country": "NL",
  "Shipping Phone": "111111111",
  Notes: "example notes",
  "Note Attributes": "Items shipped: 0",
  "Cancelled at": "",
  "Payment Method": "card",
  "Payment Reference": "123123",
  "Refunded Amount": "0.00",
  Vendor: "A Vendor",
  "Outstanding Balance": "2.95",
  Employee: "",
  Location: "",
  "Device ID": "",
  Id: "123123",
  Tags: "",
  "Risk Level": "Low",
  Source: "123123",
  "Lineitem discount": "0.00",
  "Tax 1 Name": "",
  "Tax 1 Value": "",
  "Tax 2 Name": "",
  "Tax 2 Value": "",
  "Tax 3 Name": "",
  "Tax 3 Value": "",
  "Tax 4 Name": "",
  "Tax 4 Value": "",
  "Tax 5 Name": "",
  "Tax 5 Value": "",
  Phone: "",
  "Receipt Number": "123123",
};

export {
  dummyProduct,
  dummyTopics,
  dummyShopifyCategories,
  dummyProducts,
  dummyCrystallizeTopics,
  dummyShoppifyOrder,
};
